sudo: false
language: java
jdk:
- oraclejdk8
script: ant
env:
  global:
    secure: Df5FIHnieDJj8AAwgeAh779Rs+aoJ8e9WQN0ero4OfcJ2Y1G7InBZQIGesfVR1M7EX4Hf0fvmUam9zthdwi4culk+gJeOAMM/wpCqvEUyWDTd78Cr08L7PjNW8RCq5NCYhgvO1j+IzJOA3IR6h8DSS4QGZtJqPYk65ZQ1uRyAGc=
addons:
  coverity_scan:
    project:
      name: martinpaljak/esteidhacker
      description: EstEID hacker
    notification_email: martin@martinpaljak.net
    build_command_prepend: 
    build_command: ant compile
    branch_pattern: coverity
deploy:
  provider: releases
  file:
  - esteid.jar
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: nyJNh410mWIAGdLXRQA6/TFByEjRdxk4i3sXIDBTYD3jcmgEp2BYTSi3gSMaOoNgGl2KH4VgvnT48eJrvZssF39PT4h/36SCmtOfhdWVExwJDbVSY22o24brp7VjbkN2/wAl1qF/yRKEdWF3Xkc3abzpSx27aoRS8nDEvKB5v1M=

cache:
  directories:
    - lib
