sudo: false
language: java
jdk:
- oraclejdk8
install: true
before_script:
- mkdir -p ext
- wget http://kent.dl.sourceforge.net/project/launch4j/launch4j-3/3.11/launch4j-3.11-linux.tgz
- echo "fd1b654e5024d3f58419e05da2170d44dc5e924f1f369ebee8d2fb2e9cbd2b68  launch4j-3.11-linux.tgz" | sha256sum -c
- tar -C ext -xzf launch4j-3.11-linux.tgz
- ant fetch

script:
- mvn clean compile findbugs:check package
- ant windist

env:
  global:
    secure: "Rgic0xIoeZ1qwpxttV12FLMUMMOpu/y2GCGZuYJNgy5iH8Wug8vmL3E2DqN+tfFw/e4TNhEK4OW4jrVtHwFnMJcsyw3rgCim8+tdoSi75tILXQmQv8FTom+RvIhUAnJW6VYm6uRrTC2R6S62d+EvQdZAkffzDYx5QRD6KmMiF0A="
addons:
  apt:
    packages:
      - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/esteidhacker
    notification_email: martin@martinpaljak.net
    build_command: mvn clean compile
    branch_pattern: coverity
deploy:
  provider: releases
  prerelease: true
  file:
  - esteid-app.jar
  - esteid.exe
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: "fMEY8SEhUPTa23tfnu8mAiCOR7X0fUwPPBGOp4rmwLxg/E7r3cT6JJtPff1V2DKCFCsdamIjOcr6n5Y6ayGLTnG6RjTu9AYVi1EEyB2Cf6C7xdnUvulz5yPyrSzPaDUh40CmThx5XqbANjou5p5OsNQ73QFZsY9FMR8jIVDXE8Q="


cache:
  directories:
  - $HOME/.m2
